# -*- coding: utf-8 -*-
"""IMAGE TO PENCIL SKETCH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZoO9cADpVWrLh1NqoMCqAa0p01RVfl3q

NAME-PAVNEET KAUR

DATA SCIENCE INTERN AT LGMVIP

TASK -01 :BEGINNERS LEVEL

IMAGE TO PENCIL SKETCH
"""

from google.colab.patches import cv2_imshow
from google.colab import files
import os
import cv2
import matplotlib.pyplot as plt

uploaded = files.upload()

"""ORGINAL IMAGE"""

image=cv2.imread("my image.jpg")
image=cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.imshow(image)
plt.grid(False)
plt.title("Original Image")
plt.show()

"""RGB TO GRAY SCALE IMAGE"""

image_gray =cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(image_gray, cmap="gray")
plt.grid(False)
plt.title("GRAYSCALE Image")
plt.show()

"""INVERT GRAYSCALE IMAGE"""

image_invert=cv2.bitwise_not(image_gray)
plt.imshow(image_invert,cmap="gray")
plt.grid(False)
plt.title("INVERT GRAYSCALE Image")
plt.show()

"""USING GAUSSIAN BLUR"""

image_blur=cv2.GaussianBlur(image_invert,(15,15), sigmaX=0,sigmaY=0)

"""PENCIL SKETCH IMAGE"""

image_final=cv2.divide(image_gray,255-image_blur,scale=255)
image_invert=cv2.bitwise_not(image_gray)
plt.imshow(image_final,cmap="gray")
plt.grid(False)
plt.title("PENCIL SKETCH Image")
plt.show()